# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-05 01:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_reg_email_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='acct_public',
            field=models.BooleanField(default=True, help_text='Should other users be able to see this account?'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='public_default',
            field=models.BooleanField(default=True, help_text='Should other users be able to view your links by default?'),
        ),
    ]
