# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-05 01:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigSetting',
            fields=[
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created on')),
                ('updated_on', models.DateTimeField(editable=False, verbose_name='updated on')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('config_code', models.CharField(max_length=6, unique=True)),
                ('config_description', models.CharField(max_length=100)),
                ('config_value', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['config_code'],
                'permissions': (('view_config_seting', 'Can view configuration'),),
            },
        ),
    ]
