# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-11 02:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bulk', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configsetting',
            options={'ordering': ['config_code'], 'permissions': (('view_configsetting', 'Can view configuration'),)},
        ),
    ]
