# Generated by Django 2.1.15 on 2021-05-06 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bulk', '0002_auto_20180411_0225'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configsetting',
            options={'ordering': ['config_code']},
        ),
    ]
