# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-29 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='invite_sent',
            field=models.DateField(blank=True, null=True),
        ),
    ]
