# Generated by Django 2.1.15 on 2021-05-06 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_auto_20170729_1542'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='signup',
            options={},
        ),
    ]
