# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-03 18:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created on')),
                ('updated_on', models.DateTimeField(editable=False, verbose_name='updated on')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_default', models.BooleanField(default=True)),
                ('acct_public', models.BooleanField(default=True)),
                ('display_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('url', models.URLField(blank=True, max_length=400, null=True)),
                ('notes', models.TextField(blank=True, max_length=1000, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('view_profiles', 'Can view profiles'),),
            },
        ),
        migrations.AlterModelOptions(
            name='link',
            options={'permissions': (('view_links', 'Can view links'),)},
        ),
    ]
