# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-18 13:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0004_auto_20170604_0018'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportFile',
            fields=[
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created on')),
                ('updated_on', models.DateTimeField(editable=False, verbose_name='updated on')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(blank=True, max_length=500, null=True)),
                ('import_text', models.TextField(blank=True)),
                ('import_type', models.CharField(max_length=1)),
                ('import_status', models.CharField(default='N', max_length=1)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='links.Profile')),
            ],
            options={
                'permissions': (('view_imports', 'Can view imports'),),
            },
        ),
    ]
