# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-23 14:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0005_importfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterfaceFile',
            fields=[
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created on')),
                ('updated_on', models.DateTimeField(editable=False, verbose_name='updated on')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(blank=True, max_length=500, null=True)),
                ('file_type', models.CharField(max_length=1)),
                ('text', models.TextField(blank=True)),
                ('file_format', models.CharField(max_length=1)),
                ('status', models.CharField(default='N', max_length=1)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='links.Profile')),
            ],
            options={
                'permissions': (('view_interface_files', 'Can view interface files'),),
            },
        ),
        migrations.RemoveField(
            model_name='importfile',
            name='profile',
        ),
        migrations.DeleteModel(
            name='ImportFile',
        ),
    ]
