# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-30 22:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0006_auto_20170723_1423'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='link',
            unique_together=set([('url', 'profile')]),
        ),
    ]
