# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 00:37
from __future__ import unicode_literals

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('links', '0007_auto_20170730_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='interfacefile',
            name='file_format',
            field=models.CharField(choices=[('D', 'Delicious Export File'), ('N', 'Netscape Bookmark File (Chrome/Firefox/IE)')], max_length=1),
        ),
        migrations.AlterField(
            model_name='link',
            name='status',
            field=models.CharField(blank=True, choices=[('N', 'Not found'), ('O', 'OK'), ('R', 'Redirect'), ('E', 'Error')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
