# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-12 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0009_auto_20171005_0047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='url',
        ),
        migrations.AlterField(
            model_name='interfacefile',
            name='status',
            field=models.CharField(choices=[('N', 'New - not imported'), ('Y', 'Yes - imported successfully'), ('E', 'Error - not imported')], default='N', max_length=1),
        ),
    ]
