# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-31 21:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0011_auto_20171116_0100'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='link',
            index=models.Index(fields=['profile', 'created_on'], name='links_link_profile_2e3530_idx'),
        ),
        migrations.AddIndex(
            model_name='link',
            index=models.Index(fields=['created_on'], name='links_link_created_dd3c88_idx'),
        ),
    ]
