# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-31 21:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0012_auto_20171231_2148'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='link',
            name='links_link_profile_2e3530_idx',
        ),
        migrations.RemoveIndex(
            model_name='link',
            name='links_link_created_dd3c88_idx',
        ),
        migrations.AddIndex(
            model_name='link',
            index=models.Index(fields=['profile', '-created_on'], name='links_link_profile_04714b_idx'),
        ),
        migrations.AddIndex(
            model_name='link',
            index=models.Index(fields=['-created_on'], name='links_link_created_71147e_idx'),
        ),
    ]
