# Generated by Django 2.1.15 on 2021-05-06 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0014_auto_20180310_2119'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interfacefile',
            options={},
        ),
        migrations.AlterModelOptions(
            name='link',
            options={},
        ),
        migrations.AlterField(
            model_name='genericuuidtaggeditem',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links_genericuuidtaggeditem_tagged_items', to='contenttypes.ContentType', verbose_name='content type'),
        ),
        migrations.AlterField(
            model_name='interfacefile',
            name='file_format',
            field=models.CharField(choices=[('D', 'Delicious Export File'), ('N', 'Netscape Bookmark File (Chrome/Firefox/IE)'), ('F', 'Feedly OPML File')], max_length=1),
        ),
    ]
